### ISSUE TITLE
API 이용 문의

### ISSUE THREAD

**Issue by dvlpr91** [naver/searchad-apidoc#669]
안녕하세요.

일부 엔드포인트는 기대하는 대로 응답 값이 내려오는데, 어떤 것은 그러하지 않아서요~

예를 들어, /ncc/campaigns 같은 경우엔 괜찮은데, /stats 같은 경우엔 11001 코드와, "잘못된 파라미터 형식입니다."라는 메시지를 줍니다.

![image](https://user-images.githubusercontent.com/40349371/197713406-1c9b5d9f-f0fa-4317-96cd-51bae114bb0f.png)

이미지에 보이는 표현식대로, /stats 뒤에 파라미터를 생략해보기도 했고, 아래 요청 파라미터 설명대로 id, fields, timeRange같은 경우엔 optional이 없길래 넣어보기도 했습니다. (그와중에, fields같은 경우엔 json format string이라 써있는데, timeRange와 달리, 대괄호가...?, 또, 다른 동작하는 것엔, optional이 안써있어도, 없이도 동작하는거봐선, optional이 없다해서 required는 또 아닌거같고...)

음...... 말고도, statReport 같은 경우엔 상태 값을 200으로 주면서도 응답 값은 그냥 빈 값이고....

음................ 어찌합니까 어떻게 할까요.......

**Comment by dvlpr91** [comment]
![image](https://user-images.githubusercontent.com/40349371/197906580-d1b58f53-992f-4b90-9959-aa4fc3ab15a8.png)

api 문서를 좀, 다양하게 해석하면서 별 짓을 다 해도 결과는 같네요... 울어야겠다.

**Comment by naver-searchad** [comment]
안녕하세요? 네이버 검색광고 API입니다.

 - optional 이 아닌 파라미터는 필수 파라미터입니다.
 - Stat api 에서 json format string에 대해서 말씀 드리면 예시로 제공된 파라미터를 url encoding 해서 사용하시면 됩니다.(언어에 따라 자동으로 url encoding 되기도 합니다.)
 - 예)
fields 파마미터를 예를 들면 fields=["impCnt","clkCnt"] 라고 request를 수행해야하고 이를 url encoding 하면
fields=[%22clkCnt%22,%22impCnt%22] 으로,
timeRange={"since":"2022-10-27","until":"2022-10-30"} 을 url encoding 하면
timeRange=%7B%22since%22:%222022-10-27%22,%22until%22:%222022-10-30%22%7D
으로  get 파라미터 방식으로 request하시면 됩니다.

 - statReport API 는 대용량 다운로드 방식의 비동기적인 리포트 요청을 제공합니다.
요청을 정확히 알려주시지 않으셔서 정확한 답변은 어려우나
비어서 리턴 되시는 이유는 StatReport 의 get API를 사용하신 것 같은데 생성요청하신 리포트가 존재하지 않기 때문일 것 같습니다.


감사합니다.

**Comment by dvlpr91** [comment]
optional 딱지 안붙어있어도 필수가 아닌 경우가 존재하고... 그러네요... ^^; 감솨합니다..........
