### ISSUE TITLE
Is there a call restriction for searchad api?

### ISSUE THREAD

**Issue by developerlicw** [naver/searchad-apidoc#74]
First of all, thanks for the API.
Just a question. Because the day before yesterday, I experienced the same problem with last issue: cannot download or create reports, and I thought is it because of too many requests at that time. 
Of course it is fixed now, but I still wonder is there a limit how many times I can use this API in one day time, or longer, a month?
I have searched this all over google but find no result, please tell me if there is actually a limit.
Thanks very much.

**Comment by developerlicw** [comment]
Oh sorry, I've forgot another thing.
As you know, every time naver displays an ad, it has a rank. Now I know my ad's rank, but I don't know how may ads are displayed on that search. So I am not able to know how my ad is actually functioning. Am I able to get how many ads(including mine) are displayed when my ads are clicked?
I'm looking forward to your reply, thanks very much.

**Comment by naver-searchad** [comment]
I'm sorry for late reply.
The reason the report was not generated is because there was a service failure.
I apologize for your inconvenience.

Q: **please tell me if there is actually a limit.**
A: 
NAVER Search Ad API service have only call rate restrictions. 
Except for the Masterreport and the StatReport, Usually 30 calls per second, (May be slower depending on the number of concurrent users)
The restrictions of the Masterreport and StatReport is "10 calls per second" 
(May be slower depending on the number of concurrent users also)

**Q: how may ads are displayed on that search?**
A:  You can check the maximum number of ads through the ManagedKeyword operation(http://naver.github.io/searchad-apidoc/#/tags/ManagedKeyword)
The PCPLMaxDepth property means the number of  ads are displayed on that search.
Please note the "PCPLMaxDepth" means only the number of ads exposed to PC NAVER SEARCH 
(http://search.naver.com/search.naver)

thanks

**Comment by developerlicw** [comment]
Thanks for the nice reply.
Sorry but I still have a question that when I looked into the "Estimate", I found that there are two kinds of bid estimate: normal and NPC, actually I don't quite understand what is NPC, could you please tell me about it or is there any documents about it? 
Thanks for your help very much, my best regards.

**Comment by naver-searchad** [comment]
Hi 
"NPC" means NAVER Power Content AD Product. (In other words "Contents Search AD.")

The types of ad product exposure are as follows.
![image](https://user-images.githubusercontent.com/18188635/33428120-0a0ae216-d60b-11e7-8237-0e35ce3b69aa.png)

Thanks

**Comment by developerlicw** [comment]
Thanks for the explain, I totally understand. 
I will close this issue. Thanks again for kindly answering all my questions.
