### ISSUE TITLE
Estimate: exposure minimum bid - 404 Not Found error

### ISSUE THREAD

**Issue by gmartinezarastey** [naver/searchad-apidoc#813]
Hi,
I am trying to access the estimate API to get the exposure minimum bid for my keywords. When I make the API call I get a 404 Not Found error response:

- https://naver.github.io/searchad-apidoc/#/operations/POST/~2Festimate~2Fexposure-minimum-bid~2F%7Btype%7D

# Code:
```python
import requests
import hashlib
import time
import hmac
import base64
import json

url_base = 'https://api.searchad.naver.com'
path = '/estimate/exposure-minimum-bid/id'

url = url_base + path
timestamp = int(time.time())
signature_concat = str(timestamp) + '.' + 'POST' + '.' + path 

key_bytes= bytes(secretKey , 'utf-8')
digest = hmac.new(key_bytes,
              signature_concat.encode('utf-8'),
              digestmod=hashlib.sha256
             ).digest()
secrethash = base64.b64encode(digest).decode()

headers = {'X-API-KEY': api_key, 
           'X-Customer': customer_id,
           'X-Signature': secrethash,
           'X-Timestamp': str(timestamp)}

data = {
    'device': 'PC',  # or 'MOBILE'
    'period': 'MONTH',  # or 'DAY'
    'items': ['nkw-a001-01-000003926239625'],
}
data_json = json.dumps(data)

r = requests.post(url, headers=headers, data=data_json)

print(r.json())
```

# Response:
`{'name': 'NotFound', 'status': 404, 'title': 'Not Found', 'detail': 'The requested resource could not be found'}`

Is the resource available?

**Comment by naver-searchad** [comment]
@gmartinezarastey 
Hello. This is NAVER Search AD. API manager

We're looking at the calls you send us to discover what caused the 404 error to be returned. However, since information is limited, it may take a long time. You may have just received the results shown to us without additional information such as the transaction ID, but nonetheless, if the transaction ID is present in the response you received, please let us know. All we need to verify the call message is the transaction ID and the time of the call (with timezone).
**Caution :In any case, we do not need your license key, private key and customer ID. When you give us a transaction ID or information, please make sure you don't include this information.**

Thanks.

**Comment by gmartinezarastey** [comment]
Hi @naver-searchad - thanks for responding to my issue.
The response doesn't have a transaction ID or a timestamp. I have made another call today 25th July at 09:10:37 (GMT+1) and this is the response:
`{'name': 'NotFound', 'status': 404, 'title': 'Not Found', 'detail': 'The requested resource could not be found'}`

**Comment by naver-searchad** [comment]
@gmartinezarastey 

Thanks for your reply.
We are still looking for the cause. When we're done, we'll give you a guide to making the right calls.

**Comment by naver-searchad** [comment]
@gmartinezarastey 

We were able to find the probable cause of the error you received.
Please check if "Content-Type" is set to 'application/json' in the header of your http call.
If the problem persists, please let us know. Our engineers will test other possibilities.

**Comment by gmartinezarastey** [comment]
That worked! Thanks a lot for your help
