### ISSUE TITLE
Naver SearchAds/StatReport API costs do not include 10% VAT while Naver SearchAds UI includes it

### ISSUE THREAD

**Issue by OBWiz** [naver/searchad-apidoc#860]
Hello,

We're working on a SearchAds spends connector using [Naver API (StatReport)](https://naver.github.io/searchad-apidoc/#/tags/StatReport) and we find that costs are returned without the 10% VAT while the [Naver UI](https://manage.searchad.naver.com/) shows all costs with VAT included.

Is there any way to retrieve :

- costs with VAT
- OR at least the value of VAT applied to amounts in the Naver UI form

I checked the documentation but I could not find any hint.

Thanks for your help,
Olivier.

**Comment by naver-searchad** [comment]
Hello.This is NAVER SEARCH ADs API.

The costs provided in STAT REPORT and STAT are not the amount deducted from the biz money in the account, and as you mentioned, they are excluding VAT.

You can consider two options.
1. Multiply the COST field in a general advertising performance report by 1.1 (110%).
The VAT rate is 10%, and this rate has been maintained for the past several decades. Changing this tax rate will be a very big event, so you will be aware of the tax rate change, so even if you calculate VAT with a fixed formula, you will not have to keep changing your logic, and if the VAT rate changes in the distant future, someone will know. It is extremely unlikely that you will miss this change in the VAT rate and not be able to modify the logic.
The biggest disadvantage of this method is that the total COST on the report may be different from the amount you actually paid.
This is because the COST in the report does not distinguish between refundable biz money and non-refundable biz money (for example, biz money charged with free biz coupons). We do not categorize the two when generating report data.

2. The second method is to use BIZ MONEY information API. At the link below, you can check the specifications of BIZ MONEY API. 
https://naver.github.io/searchad-apidoc/#/tags/Bizmoney(https://naver.github.io/searchad-apidoc/#/tags/Bizmoney)
The UI(MANAGE.SEARCHAD.NAVER.COM Biz MONEY MENU)  also uses the same API, so you can get the same information items as the UI. (Of course, items containing personal information that cannot be provided through the NAVER SAERCH AD. API due to legal reasons, such as card information used for payment, cannot be searched through the API.)

I hope my answer was helpful to you.

Thnak you

**Comment by OBWiz** [comment]
Thanks for your answer !

The easiest option is certainly multiplying the cost with the VAT rate.
