### ISSUE TITLE
Stat Report Sample: 

### ISSUE THREAD

**Issue by Gregcake** [naver/searchad-apidoc#89]
Hi,

I'm running StatReportSample.java. When I change REPORT_TYPE to EXPKEYWORD, report status always returns as NONE, even after waiting some time between each query.

Additionally, when I change REPORT_TYPE to:
AD_DETAIL
AD_CONVERSION
AD_CONVERSION_DETAIL
ADEXTENSION
ADEXTENSION_CONVERSION
NAVERPAY_CONVERSION,

I get the error `java.lang.Exception: 400 Bad Request. X-Transaction-ID: B19EH5SDPPNSN, Response Body: {"code":11001,"message":"??? ???? ?????."}`

I am only able to run StatReportSample.java when report type is set to AD.

Pls help!

**Comment by naver-searchad** [comment]
Hi 

The report only generates data for the account that is running the ad. "None" means that the information on the date you searched for does not have ad serving data 

Thanks

**Comment by Gregcake** [comment]
Is there a way to find out what the dates that have data are? Also is it possible to query over a time range instead of a single date (ie. 20170630 - 20180201) ?

**Comment by naver-searchad** [comment]
Hi 

We apologize for the delayed response.
In order to check the date of data existence, there is no way to make a create call by date.
We do not offer the ability to search by period.
There is no regular way, but there is a roundabout way. It is a way to check the existence of data by date using the quick response STAT.

Thank you
