### ISSUE TITLE
Error code 20001

### ISSUE THREAD

**Issue by Gregcake** [naver/searchad-apidoc#90]
Hi,

What does this error code mean?
`java.lang.Exception: 500 Internal Server Error. X-Transaction-ID: B1CFPREP1PIF6, Response Body: {"code":20001,"message":"???? ??? ??? ???? ????. ??? ???? ??? ?????."}`

Thanks

**Comment by naver-searchad** [comment]
Hi 

I'm sorry for late reply.
Error code 20001 means that the report generation failed.

There are a variety of cases where creation fails. 
In general, there is a problem with our report generation system.
At the end of January, there was a failure to generate reports due to servers changes. 
It seems to be the influence at that time. Generally, a normal retry will occur.

Thanks
